### ISSUE TITLE
Guidance on how to create an ordered stream of results?

### ISSUE THREAD

**Issue by jackgerrits** [danieldg/ordered-stream#15]
For my use case I have several streams of results that need to be combined, if an error is hit it seems reasonable for the overall stream to return the error and stop processing. The items within the result are ordered.

I was wondering if there is any guidance or examples of using results within. I see two possible ways to go about this:

- Make sure the error variant of the result has some kind of ordering. Perhaps by storing the ordering of the previous valid value and using that to order an error that may occur
- Or, assign some "minimum" value to results to ensure they are produced. However, I am wondering how to interpret this sentence  ["Each stream must produce values that are in ascending order according to this function, although there is no requirement that the values be strictly ascending."](https://docs.rs/ordered-stream/latest/ordered_stream/trait.OrderedStream.html#associatedtype.Ordering). Does this mean that ascending or equal to is okay, but to go backwards is invalid?

Thanks in advance.

**Comment by danieldg** [comment]
If errors always cause the end of the stream, then the best way to order them is to sort them "after" all other possible elements - either by using !0u64 as an ID, or as if the ordering was `#[derive(PartialOrd)] enum Order { Value(...), Error }` - this is how zbus works.  Otherwise, you would need to include some kind of "current location" marker for transient errors.

Basically the stream needs to return something like "1, 2, 2, 3, 5, 1001, 1001, 2000"
